WITH RECURSIVE CAH AS (SELECT 0 AS HOUR
                       UNION ALL
                       SELECT HOUR + 1
                       FROM CAH
                       WHERE HOUR < 23)
SELECT CAH.HOUR, COUNT(HOUR(AO.DATETIME)) AS COUNT
FROM CAH LEFT JOIN ANIMAL_OUTS AS AO ON CAH.HOUR = HOUR(AO.DATETIME)
GROUP BY CAH.HOUR
ORDER BY CAH.HOUR